'use strict';

// ── WENDY QUOTES ──
const Q = {
  gameStart: [
    "Shuffle up and pray, child.",
    "Bless your heart. You'll need it.",
    "I've seen better hands at bingo night.",
    "Let us begin. May God have mercy on your tiles.",
    "I do hope you've been practising. I have.",
    "Remember: pride goeth before a fall. Just saying.",
    "The convent hasn't lost a game since 1987. Today will be no different.",
    "I have blessed these tiles. My blessing, not yours.",
    "The Lord shuffles in mysterious ways.",
  ],
  herTurn: [
    "Calculating divine strategy...",
    "The Lord is guiding my hand.",
    "Patience is a virtue. Mine is running out.",
    "Mm. Yes. Interesting.",
    "Don't rush me. Holiness takes time.",
    "I am deliberating. Prayerfully.",
    "A moment of contemplation before I crush you.",
    "Every tile a prayer. Every play a sermon.",
    "Processing. Divinely.",
  ],
  herScores: [
    "God rewards the devout — and my arithmetic!",
    "That's FIFTEEN. Count it, child.",
    "The Lord provides. In multiples of five.",
    "Ha! Did you see that? Did you SEE that?!",
    "Ten points for Sister Wendy. None for you.",
    "I am SO good at this it frightens me.",
    "Blessed are the scorers, for they shall have points.",
    "Do try to keep up.",
    "Another five points closer to heaven.",
    "I don't mean to gloat. Actually, yes I do.",
  ],
  herBigScore: [
    "Sweet Mary! That's a miracle!",
    "TWENTY-FIVE! I'm basically a prophet.",
    "The rosary pays off at last!",
    "That. Was. GORGEOUS.",
    "Lord, I am not worthy. But also, I totally am.",
    "Twenty points! I need a moment to collect myself.",
    "That's what we call divine intervention, child.",
  ],
  playerScores: [
    "Hmph. Beginner's grace.",
    "Don't get used to that.",
    "Fine. Enjoy it. It won't last.",
    "Even a broken clock...",
    "I'll allow it. Once.",
    "I see you've been practising. Unfortunately.",
    "You lucky, lucky sinner.",
    "That was... acceptable. Barely.",
    "I'm not angry. I'm disappointed. Play again.",
  ],
  playerBigScore: [
    "TWENTY?! That's... no. No, I refuse to acknowledge it.",
    "How. Just... how.",
    "I'm going to need a moment of silent prayer.",
    "That should not have happened. God is testing my patience.",
    "Fine! FINE. But this changes nothing.",
  ],
  herCantPlay: [
    "Drawing like rosary beads... give me strength.",
    "Lord, why hast thou forsaken my boneyard.",
    "I must draw. Do not laugh.",
    "This is humiliating.",
    "These tiles are conspiring against me.",
    "Not ideal. But I remain faithful.",
    "A temporary setback. God is testing me.",
    "The boneyard gives and the boneyard takes away.",
  ],
  playerCantPlay: [
    "Even your dominoes are hiding from you.",
    "The boneyard awaits, sinner.",
    "Draw. Draw. Draw. Like your strategy.",
    "God is testing you. You are failing.",
    "Oh dear. Oh, dear dear dear.",
    "Perhaps prayer would help. I wouldn't know.",
    "You seem stuck. I am not stuck. Interesting contrast.",
    "The tiles have abandoned you. Can't say I blame them.",
    "Tsk. Tsk. Tsk.",
  ],
  herDomino: [
    "DOMINO! The Lord's work is done.",
    "Blessed are the swift, for they shall domino.",
    "And THAT is how a nun plays dominoes.",
    "In nomine Patris et Filii — DOMINO!",
    "I have been playing dominoes since before you were born. It shows.",
    "Done. Simply done. Say your prayers.",
    "Empty hand, full heart. The way of the righteous.",
    "Domino! Count your remaining tiles and weep.",
  ],
  playerDomino: [
    "Fine. You got lucky.",
    "I let you win. For your moral development.",
    "Enjoy this. It won't happen again.",
    "Well. I'll be saying extra prayers tonight.",
    "I am not upset. I am disappointed. There is a difference.",
    "A fluke. A statistical aberration. Nothing more.",
    "I see. Very good. I shall remember this.",
    "God grants even the undeserving occasional victory.",
  ],
  blocked: [
    "This is what happens when nobody listened at Mass.",
    "We are ALL blocked. Like my sinuses. And your strategy.",
    "A draw. How very... Protestant of us.",
    "The tiles have spoken. Neither of us wins.",
    "God, in His wisdom, has declared a tie. I remain suspicious.",
    "Stalemate. The Lord works in mysterious ways. Frustrating ones.",
  ],
  herDouble: [
    "A divine double! Providence smiles.",
    "Double blessing!",
    "The Lord gives in pairs.",
    "Doubles are my speciality. Along with humility.",
    "A double! The angels rejoice.",
    "Symmetry. The Lord loves symmetry.",
  ],
  playerDouble: [
    "Even a broken clock...",
    "Don't celebrate. It's one double.",
    "Fine. Double. Very impressive.",
    "Enjoy your double. I have a plan.",
    "A double. Noted. Unimpressed.",
  ],
  closeScore: [
    "This is uncomfortably close. I am uncomfortable.",
    "Neck and neck. As the Lord intended. I suppose.",
    "One of us will pull ahead. It will be me.",
    "A tight game. My heart rate is elevated. Spiritually.",
  ],
  wendyLosing: [
    "This is merely a tactical retreat.",
    "I am luring you into complacency.",
    "Don't mistake my generosity for weakness.",
    "I am... recalibrating.",
    "The Lord tests me today. Severely.",
  ],
  angry: [
    "You think this is FUNNY?!",
    "Lord give me strength.",
    "This is NOT over.",
    "I am vexed. The Lord sees my vexation.",
    "Right. That's enough of that.",
    "Oh, we're doing THIS, are we.",
    "I have never been so disrespected by a dominoes board.",
  ],
  smug: [
    "As I was saying...",
    "Mm-hmm. As expected.",
    "Naturally.",
    "Of course.",
    "I did mention this would happen.",
    "The tiles never lie. Unlike some people.",
    "Just as the scriptures predicted.",
    "I am nothing if not consistent.",
  ],
  commentary: [
    "The board is getting interesting.",
    "I see what you're up to. Don't think I don't.",
    "This is a fascinating position. For me.",
    "The endgame approacheth.",
    "Have you considered a different career?",
    "I'm keeping score in more ways than one.",
    "God sees all dominoes played.",
    "The chain reveals the soul of the player.",
    "An intriguing move. Wrong, but intriguing.",
    "I respect the attempt. I do not respect the result.",
  ],
  playerCombo: [
    "Stop. Just... stop.",
    "How are you DOING this?!",
    "Multiple scores?! I am having a theological crisis.",
    "Lord, is this some kind of test for me specifically?",
    "The audacity. The absolute audacity.",
    "That's twice in a row. I need a biscuit.",
  ],
  wendyPanic: [
    "I see what I must do. The Lord will provide.",
    "This is fine. Everything is fine.",
    "My tiles are entirely under control. Obviously.",
    "Do NOT look at my hand.",
    "I have a plan. Several plans. None of them are working.",
    "I am down to my last tile. I remain serene. Externally.",
  ],
  almostWin: [
    "One more round and victory is mine. Don't celebrate yet.",
    "I can taste the victory. It tastes like righteousness.",
    "I am merely warming up. The final blow comes now.",
    "This is almost over. For you.",
    "Say your prayers — I'm about to end this.",
  ],
  playerAlmostWin: [
    "Fine. You're close. But close is not enough.",
    "Don't count those chickens, child.",
    "You seem pleased. Interesting. Premature.",
    "I have been here before. I always rally. Watch.",
    "One good hand and everything changes. Mine.",
  ],
  frustrated: [
    "WHY are the tiles doing this to me.",
    "I am serene. I AM SERENE.",
    "This is not going the way I planned. At ALL.",
    "The Lord is testing my patience. Severely.",
    "I need a moment. And possibly a rosary.",
    "Every domino game is a spiritual trial. This is especially trial-y.",
  ],
};

// ── HELPERS ──
function randQ(key) {
  const arr = Q[key] || Q.herTurn;
  return arr[Math.floor(Math.random() * arr.length)];
}

// ── PIP PATTERNS (3×3 grid positions) ──
const PIP = {
  0: [],
  1: [4],
  2: [2,6],
  3: [2,4,6],
  4: [0,2,6,8],
  5: [0,2,4,6,8],
  6: [0,3,6,2,5,8],
};
