/* GENERATED by ops/legal-kit/build.py — do not hand-edit.
 *
 * The vendor facts live in ops/legal-kit/properties.json and the prose lives in
 * build.py, so that one policy naming N vendors cannot be right in one repo and
 * a month stale in the other seven. Change it there and re-run:
 *
 *     ops/legal-kit/build.py sister-wendy
 */

export const UPDATED = '24 August 2026';
export const CONTACT = 'play@screwcapholdings.com';

export const ABOUT_HTML = `
<p>Sister Wendy plays All-Fives dominoes and she has opinions about your tile choices. RaceHorse rules, two seats, and a nun who was trained on self-play rather than on politeness.</p>
<p>The variant matters and gets stated plainly because the studio makes two dominoes games and they are not the same game. This one is RaceHorse only, two players only. DoubleFives is Standard by default with several variants and two, three or four seats. A rule carried across from one to the other will simply be wrong.</p>
<p>She talks while you play. That is a feature: the commentary is where the reasoning is, and the fastest way to get better is to notice which of your plays she has something to say about.</p>

<h2>How it pays for itself</h2>
<p>Advertising on the free tier — on menus, between hands and on end screens, never during a
   live hand — plus an optional <a href="https://screwcap.gumroad.com/l/sisterwendy">one-time ad-free unlock</a>. That is
   the whole business model for this game. Which analytics and advertising vendors we let near
   you is listed by name in the <a href="/privacy.html">Privacy Policy</a>; if a tool sets a
   cookie, it is in there.</p>

<h2>Who makes it</h2>
<p>Sister Wendy's Dominoes is made by Screwcap Games, LLC, a small independent studio in Walworth County, Wisconsin. We build games
   about judgment under uncertainty — monetary policy, commodity markets, household finance —
   and a few card and domino games that are just games. The rest of the catalogue is at
   <a href="https://screwcap.games">Screwcap.Games</a>.</p>
<p>Bugs, corrections, licensing, or an argument about the rules:
   <a href="mailto:play@screwcapholdings.com">play@screwcapholdings.com</a>. Corrections to the data or the history get
   answered first — if something here is factually wrong, we want to know before a player
   does.</p>
<div class="aside">The honest scale of this: it is a small studio, the games are made because
   they are interesting, and the target is a drink at the end of the day rather than a
   yacht.</div>
`;
