import DailyContemplation from '@/components/DailyContemplation';
import PaintingAnalyzer from '@/components/PaintingAnalyzer';

export default function Home() {
  return (
    <div className="min-h-screen" style={{ background: 'linear-gradient(180deg, #f7f3e9 0%, #ece8d9 100%)' }}>
      {/* Header */}
      <header className="pt-16 pb-12 text-center px-4">
        <div className="text-[#c9a84c] text-xs tracking-[0.5em] uppercase mb-5 font-[family-name:var(--font-playfair)]">
          &#9670; &#9670; &#9670;
        </div>
        <h1 className="font-[family-name:var(--font-playfair)] text-4xl md:text-5xl font-bold text-[#1c0f07] mb-4 tracking-wide">
          Sister Wendy
        </h1>
        <p className="text-[#5c3d28] text-base italic max-w-sm mx-auto leading-relaxed">
          An art guide. A contemplative voice.<br />
          A painting seen as if for the first time.
        </p>
        <div className="text-[#c9a84c] text-xs tracking-[0.5em] uppercase mt-5 font-[family-name:var(--font-playfair)]">
          &#9670; &#9670; &#9670;
        </div>
      </header>

      {/* Main content */}
      <main className="max-w-4xl mx-auto px-4 pb-24">
        <DailyContemplation />

        <hr className="ornamental-rule mb-16" />

        <PaintingAnalyzer />
      </main>

      {/* Footer */}
      <footer className="text-center pb-10 px-4">
        <p className="text-[#7a6248] text-xs leading-relaxed max-w-md mx-auto">
          Contemplations generated by Claude, in the spirit of Sister Wendy Beckett (1930&ndash;2018).<br />
          Paintings from the{' '}
          <a
            href="https://www.metmuseum.org/art/collection"
            target="_blank"
            rel="noopener noreferrer"
            className="underline hover:text-[#8b6914] transition-colors"
          >
            Metropolitan Museum of Art Open Access Collection
          </a>.
        </p>
      </footer>
    </div>
  );
}
